### ISSUE TITLE
building TLE from linestring- ecc and ArgOfPer?

### ISSUE THREAD

**Issue by RJ3** [bwinkel/cysgp4#11]
Maybe this is a stupid question because of the way SGP4 works.

I'm using `tle_linestrings_from_orbital_parameters` function and noticed it is missing entries for Eccentricity and Argument of Perigee. Could this be added or is it not necessary? As-is the TLE only has 4 orbital elements, and it would need 6 to be complete.
https://github.com/bwinkel/cysgp4/blob/afdd4bcfced2ce69de4dab864df002eb236f476b/cysgp4/utils.pyx#L245

**Comment by bwinkel** [comment]
Not at all a stupid question! In fact, it was me who made a stupid mistake ;-)

The function is based on a Jupyter notebook by @cbassa [see starlink_sunlit_satellites.ipynb](https://github.com/cbassa/satellite_analysis). For the SpaceX/Starlink constellation, the two orbital parameters that you mention weren't necessary. So I simply forgot to add them to the more general 'tle_linestrings_from_orbital_parameters' function. I will implement this asap.

Thanks for letting me know.

**Comment by bwinkel** [comment]
I implemented a fix. Would it be possible for you to check if this works for you, before I make a new release?

**Comment by RJ3** [comment]
Thanks for your quick reply. That makes sense that the LEO objects didn't need those elements!
I'll test out the new changes now!
