### ISSUE TITLE
error in create_constellations

### ISSUE THREAD

**Issue by fdivruno** [bwinkel/cysgp4#14]
In Starlink example the create_constellation function gives an error when generating large number of satellites.
I tried to generate 30000 satellites from the latest Starlink filing and is says:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: TLE line string must have 69 characters
Exception ignored in: 'cysgp4.utils.tle_checksum'
ValueError: TLE line string must have 69 characters

If I change the sat_nr from 80000 to 1, the error dissapears. As we discussed this is related to the maximum number of digits that the TLE admits for satellite number.

**Comment by bwinkel** [comment]
Thanks, @fdivruno!

Indeed, TLEs must have at most a 5-digit ID. I'll change the `create_constellation` function in the notebook and add some value-checks to the `tle_linestrings_from_orbital_parameters` routine for better user feedback.
