### ISSUE TITLE
tles_from_text only works with '\r\n' line delimiters

### ISSUE THREAD

**Issue by atrawog** [bwinkel/cysgp4#17]
I had problems parsing the Starlink TLE from Celestrak with tles_from_text () and only got it to work after rewriting the line delimiters to '\r\n'.

```
>  tles = np.array(tles_from_text(starlink_tle))
>  print(len (tles))
0
```

```
>  starlink_tle_rn=('\r\n'.join(starlink_tle.split('\n')))
>  tles_rn = np.array(tles_from_text(starlink_tle_rn))
>  print(len(tles_rn))
792
```

**Comment by bwinkel** [comment]
Thanks, @atrawog. That is something, which I thought I had fixed. But apparently, I forgot about it or something. On my machine, the data from Celestrak already includes the "\r", which makes this a little inconvenient. I will fix the issue with the next release.
