### ISSUE TITLE
Natively support space-track style TLEs

### ISSUE THREAD

**Issue by michaeldcruze** [bwinkel/cysgp4#24]
I'd like to suggest cysgp4 is modified to natively support TLEs in the format that space-track provides, which lack a "name" line.
It isn't especially difficult to modify a bulk TLE string from space-track to insert a fake name line, however it would certainly be nice if cysgp4 could handle space-track bulk TLEs natively.

**Comment by bwinkel** [comment]
Thanks a lot for the proposal, @michaeldcruze. I'll try to implement this as soon as possible.
