### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by cbassa** [bwinkel/cysgp4#3]
The links to the user manual and jupyter notebooks are dead.

**Comment by bwinkel** [comment]
Wow, you're are fast. I'm still working on Azure-Pipeline integration and everything, which is why I created the Github repository already. The manual is not yet finished. Stay tuned ;-)

**Comment by bwinkel** [comment]
Please let me know, if you have suggestions with respect to the user manual or ideas for further tutorials.
