### ISSUE TITLE
Accuracy issues

### ISSUE THREAD

**Issue by cbassa** [bwinkel/cysgp4#9]
The `cysgp4` results appear to differ from recent versions of `libsgp4` as well as `python-sgp4`.

For the TLE below, both `libsgp4` and `python-sgp4` provide comparable results upto 80 days past the epoch, while the results from `cysgp4` (both `Satellite` and `propagate_many`) differ significantly. See the test code at https://gist.github.com/cbassa/0b276a1161341e4b978c14afcaa796c6

```
libsgp4
  115200.00000000   -1600.13819675   20578.04200191   39366.87452457   -1.555873584   -0.005772961   -0.704798817
python-sgp4
  115200.00000000   -1600.14150349   20578.07771344   39366.88852032    -1.55586730    -0.00576829    -0.70480021
cysgp4 propagate_many
  115200.00000000    1027.59791387   20468.99035015   40343.94400071    -1.55449739     0.14614740    -0.40918630
cysgp4 Satellite
  115200.00000000    1027.59791387   20468.99035015   40343.94400071    -1.55449739     0.14614740    -0.40918630

```

The TLE I used is the following (which can be stored as `SGP4-VER.TLE` to use in `libsgp4`'s `runtest` tool):
```
# USA 259
1 40344U 14081A   19289.95767003 0.00000526  00000-0  00000-0 0    01
2 40344  63.4408 358.0868 7184845 269.5721  15.5423  2.00643946    03     0.00    115200.0       7200.00

```

It is unclear to me if this is an issue with the `libsgp4` version used in `cysgp4` or not; so far my tests could not answer that question. How difficult would it be to update `libsgp4` in `cysgp4` to the latest version?

**Comment by bwinkel** [comment]
I noticed the difference between `python-sgp4` and `cysgp4` before, but wasn't sure if it's something to worry about given that they are based on different C-libraries. I didn't realize that there was a newer version of `libsgp4`. I shall update my wrapper to use the most recent version, but this may take a couple days. It should not be too difficult, although I'll have to make some patches (some constructors are missing and for windows compatibility). Thanks for letting me know!

**Comment by cbassa** [comment]
Thanks in advance for updating `libsgp4`!

Which `libsgp4` commit is used for the current version? I'd like to test that commit of `libsgp4` to make sure the problem is indeed there.

**Comment by bwinkel** [comment]
I think it is faf87bed, rather old as I realize now. It seems, I downloaded a zip version some years ago, before the repository on GitHub even appeared.

**Comment by bwinkel** [comment]
I just opened a PR, which makes use of the latest `libsgp4`. The results of your test script are

```
  115200.00000000   -1600.13820920   20578.04200186   39366.87451894    -1.55587358    -0.00577296    -0.70479882
```
Strange thing is that there is still a small deviation from your `libsgp4` result.

By-the-way, would you expect reasonable results for 80-day offsets? I always thought one ought to use TLEs, which have an epoch that is close to the desired time.

**Comment by bwinkel** [comment]
Forgot to say, that I didn't update the tests yet. If you find the time, could you give the new version a quick test? I'm going to change the test cases soon.

**Comment by cbassa** [comment]
Your PR gives me the same results as you, thanks!
`115200.00000000   -1600.13820920   20578.04200186   39366.87451894    -1.55587358    -0.00577296    -0.70479882`

The small differences are curious, but could perhaps be attributed to numerical precision? At these levels I'm not too worried about this, though I'm happy to help investigate further.

I agree that 80 day old TLEs can hardly be trusted, but in my experience the predictions for these high orbits don't deteriorate as fast as the lower ones. For objects whose orbits are determined from amateur observations, TLEs can get quite old due to visibility constraints. [This observation](https://imgur.com/a/llI9jkz) led me to find this issue; the green prediction for object 40344 is for a numerically propagated orbit, while the blue is using SGP4/SDP4, both using an 80 day old state vector. These are predictions using the Dundee SGP4/SDP4 model, but when using your `cysgp4` implementation, the blue prediction was not in the field of view. Fortunately your new version reproduces the [plot nicely in python](https://imgur.com/a/d6NKmjW).
